### ISSUE TITLE
Users should be able to send to 00 via SMTP. 

### ISSUE THREAD

**Issue by liltechnomancer** [technomancy-dev/00#8]
Users may not be able to send via an API so 00 should support SMTP. 

This may be a solution https://github.com/maxneuvians/pique

**Comment by liltechnomancer** [comment]
Will need to solve for auth.

**Comment by rapcal** [comment]
Would make it play a lot nicer with rails applications (actionmailer). Hope you manage to solve this soon.

**Comment by liltechnomancer** [comment]
> Would make it play a lot nicer with rails applications (actionmailer). Hope you manage to solve this soon.

Any interest in helping test this? I got a working implementation done today after seeing your post, but merging it would require I fork and update an Elixir library. Would love to see if it even works as is with something like Rails before going through the trouble. I could make a branch for you.

**Comment by liltechnomancer** [comment]
I made the branch [recieve-smtp](https://github.com/technomancy-dev/00/tree/feature/receive-smtp) for this. 
It currently doesn't have auth options, but should be enough to know if it works as expected. 

I tested it with telnet and it seems good from there.

**Comment by rapcal** [comment]
Awesome! I will try to set it up and deploy it this week.

**Comment by rapcal** [comment]
@liltechnomancer I'm sorry but I'm a little lost about how to configure the smtp settings. Should I use the credentials created in 00?

Below you'll find a sample config hash.

```ruby
config.action_mailer.smtp_settings = {
  address:         'smtp.gmail.com',
  port:            587,
  domain:          'example.com',
  user_name:       '<username>',
  password:        '<password>',
  authentication:  'plain',
  enable_starttls: true,
  open_timeout:    5,
  read_timeout:    5
}
```

**Comment by liltechnomancer** [comment]
Currently it doesn't do any authentication, which is the one of the things keeping me from releasing as is. 

It starts an smtp server with the application on port 2525, so I think that is all you really need to set in the action mailer settings to test it. 

When I do add auth, it will be PLAIN and take the API token you can generate in the dashboard as both username and password. 

EDIT

Sorry for not explaining this initially.

**Comment by rapcal** [comment]
Not sure if I'm doing something wrong, @liltechnomancer, but 00 docker container is running (can login normally on port 4000), rails is configured as below, and I'm getting `Connection refused - connect(2) for "localhost" port 2525`

```ruby
config.action_mailer.delivery_method = :smtp
config.action_mailer.smtp_settings = {
    address: "localhost",
    port: 2525
}
```

**Comment by liltechnomancer** [comment]
When you start the app do you get a log like: 

`[notice] :gen_smtp_server listening on {0, 0, 0, 0}:2525 via :tcp`

<img width="564" alt="Screenshot 2024-10-22 at 10 39 15 PM" src="https://github.com/user-attachments/assets/d49b456f-4b22-499a-a071-ca03c8794549">

If yes, could you try `telnet 127.0.0.1 2525` and see if that connects fine?

**Comment by rapcal** [comment]
I can't see this log entry.

This is probably due to my absolute illiteracy when it comes to docker. Should I build the image from the provided Dockerfile?

I'm simply doing `docker run -it --platform linux/arm64 --env-file .env -p 4000:4000 "liltechnomancer/double-zero:0.2.1"`

**Comment by liltechnomancer** [comment]
@rapcal I see, yes to test this you would need to build locally. So you would run 
`docker build --tag 'double-zero' --file ./Dockerfile .` 
then 
`docker run -it --env-file .env -p 4000:4000 'double-zero'`

**Comment by rapcal** [comment]
Thanks and so sorry for the confusion.

I'm now seeing this line in the logs

`02:07:13.941 [notice] :gen_smtp_server listening on {0, 0, 0, 0}:2525 via :tcp`

I can access localhost:4000 but the first time I try to register a user, an error pops up

```bash
02:07:34.151 [error] GenServer #PID<0.3021.0> terminating
** (UndefinedFunctionError) function Pandex.html_to_plain/1 is undefined (module Pandex is not available)
    Pandex.html_to_plain("<h1>Hi redacted@gmail.com,</h1>\n<p>You can confirm your account by visiting the URL below:</p>\n<p><a href=\"https://localhost/users/confirm/4nL_QPqAZpqqfooPPzYWsL4J1xUbzWYYKxa1KfcQNOs\">confirm email</a></p>\n<p>If you didn't create an account with us, <strong>please ignore this.</strong></p>\n")
    (phoenix_00 0.1.0) lib/mail_man.ex:75: Phoenix00.MailMan.render_html_to_plain_text/1
    (phoenix_00 0.1.0) lib/mail_man.ex:44: Phoenix00.MailMan.make_map/1
    (phoenix_00 0.1.0) lib/mail_man.ex:10: Phoenix00.MailMan.letter/1
    (phoenix_00 0.1.0) lib/phoenix_00/messages/services/send_email.ex:19: Phoenix00.Messages.Services.SendEmail.proccess_and_send_email/1
    (phoenix_00 0.1.0) lib/phoenix_00/accounts/user_notifier.ex:8: Phoenix00.Accounts.UserNotifier.deliver/3
    (phoenix_00 0.1.0) lib/phoenix_00_web/live/user_registration_live.ex:78: Phoenix00Web.UserRegistrationLive.handle_event/3
    (phoenix_live_view 0.20.14) lib/phoenix_live_view/channel.ex:507: anonymous fn/3 in Phoenix.LiveView.Channel.view_handle_event/3
Last message: %Phoenix.Socket.Message{topic: "lv:phx-GADy0x0v-WVIzwJo", event: "event", payload: %{"event" => "save", "type" => "form", "value" => "_csrf_token=BQgYOTRbPSxQYl8sP39HBTkQB3YrXhoccmPwloHE9VrfqGqkCYXFx5xv&user%5Bemail%5D=redacted%40gmail.com&user%5Bpassword%5D=redacted"}, ref: "40", join_ref: "4"}
```

When trying to send from rails I still get `Connection refused - connect(2) for "localhost" port 2525`

telnet is not successful as well for port 2525, although it works for port 4000

```bash
$ telnet 127.0.0.1 2525
Trying 127.0.0.1...
telnet: connect to address 127.0.0.1: Connection refused
telnet: Unable to connect to remote host
```

**Comment by liltechnomancer** [comment]
Interesting. I don't know why Pandex would be throwing an error it should be in the docker container. I will work on this a bit more and get back to you.

**Comment by rapcal** [comment]
Sure. Keep in mind it could be something I'm doing wrong 😬 

But I've successfully built the container according to your rules and the logs now show the `gen_smtp_server` line.

**Comment by rapcal** [comment]
Hey @liltechnomancer ! Anything I can do to help move this forward? Dying to replace Mailgun in prod :-D

**Comment by liltechnomancer** [comment]
> Hey @liltechnomancer ! Anything I can do to help move this forward? Dying to replace Mailgun in prod :-D

Good timing, I am actually very close to getting this ready! Hoping I can merge it later today. I am running tests in prod right now.

**Comment by rapcal** [comment]
That's amazing!

**Comment by liltechnomancer** [comment]
This landed in pro today, should be coming to the OS version soon 🍾

**Comment by rapcal** [comment]
Genius! Thanks :) Grabbing the credit card!

**Comment by rapcal** [comment]
And BAM! Thanks a lot! ❤️ 

![CleanShot 2024-12-18 at 20 55 43@2x](https://github.com/user-attachments/assets/88c8cf88-5cdd-4598-9f10-d9b1d1403485)

[edit - hid the promo code]

**Comment by liltechnomancer** [comment]
Thanks man, it means a lot! ❤️

**Comment by rapcal** [comment]
Good luck in your enterprise! You certainly deserve it.
